### PR TITLE
Update forgotpassword.inc.php

### PR DESCRIPTION
**Pull request by stuke2**
line 36: [[+ confirmUrl]] => [[+confirmUrl]]

### CODE REVIEW

**Comment by stuke2** [comment]
Hi, 
So i saw there was a small typo on this file.
This is my first time ever i wanted to report this
I hope i did it ok.

**Comment by Jako** [comment]
Thanks, the translations of the package could be done on [Crowdin](https://crowdin.com/project/modx-login). I will add this there.

**Comment by Jako** [comment]
Added by https://github.com/modxcms/Login/commit/72056ebb3e2099637b80c7ccf4109c2982d83183

**Comment by Jako** [comment]
Added by https://github.com/modxcms/Login/commit/72056ebb3e2099637b80c7ccf4109c2982d83183

**Pull request closed without merging**
